language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.1 WP_MULTISITE=0
    - WP_VERSION=4.1 WP_MULTISITE=1

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  exclude:
    # We really only need to verify that each PHP/WP combination works generally, not that multisite works between them
    - php: 5.4
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 5.5
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    # Only test latest version of WP with HHVM
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=4.1 WP_MULTISITE=1
    # Only test latest version of WP with PHP 7.0+ because 4.1 won't work at all
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=4.1 WP_MULTISITE=1
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.1 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      elif [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      fi
    - which phpunit
    - phpunit --version

script:
    - phpunit
